# 1. Base image for installing dependencies
FROM node:18-alpine AS deps
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# 2. Builder image for building the application
FROM node:18-alpine AS builder
WORKDIR /app
# Copy dependencies from the 'deps' stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# The prisma client is generated by the postinstall script in package.json
# Build the application
RUN npm run build

# 3. Production image
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone output from the builder stage.
# This includes the server.js file, and all necessary node_modules.
COPY --from=builder /app/.next/standalone ./

# Copy the public and static folders
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

# The standalone output includes the prisma schema, so we don't need to copy it manually
# but we need to ensure the prisma client files are there.
# Next.js standalone output should handle this.

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]